### ISSUE TITLE
Remote upgrade for NAND based devices

### ISSUE THREAD

**Issue by sque** [hwmn/hwmnos#7]
Right now, OpenWRT does not support _sysupgrade_ for devices that have different partitions for kernel and rootfs. This makes it impossible to remotely upgrade a mikrotik routerboard. Even worst, that there is no way to upgrade and still keep the same configuration automatically.

HwmnOS seeks to adapt fast on the problems of HWMN, this means that all devices should have a VERY easy way to upgrade to the latest version. And right now we don't have one for routerboards.

**Comment by gkiagia** [comment]
This is supported now in HwmnOS
